# Lab Exercise 2

Tan Bing Shien WQD180104

## 1. Prequisite
Import cleaned dataset from **Lab Exercise 1**.

In [1]:
# Import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn import tree
# --- Visualize Decion Tree ---
from graphviz import Source
from sklearn import tree
from IPython.display import SVG

In [2]:
# Import dataset
df = pd.read_csv('lab2.csv')

Print dataset information to refresh your memory.

In [3]:
df

,TargetB,GiftCnt36,GiftCntAll,GiftCntCard36,GiftCntCardAll,GiftAvgLast,GiftAvg36,GiftAvgAll,GiftAvgCard36,GiftTimeLast,...,PromCntCardAll,StatusCat96NK,StatusCatStarAll,DemCluster,DemAge,DemGender,DemHomeOwner,DemMedHomeValue,DemPctVeterans,DemMedIncome
0,0,2,4,1,3,17.0,13.50,9.25,17.000000,21,...,13,A,0,0,60.0,F,0,0,0,40491.444249
1,0,1,8,0,3,20.0,20.00,15.88,14.224431,26,...,24,A,0,23,67.0,F,0,186800,85,40491.444249
2,1,6,41,3,20,6.0,5.17,3.73,5.000000,18,...,22,S,1,0,60.0,M,0,87600,36,38750.000000
3,1,3,12,3,8,10.0,8.67,8.50,8.670000,9,...,16,E,1,0,60.0,M,0,139200,27,38942.000000
4,0,1,1,1,1,20.0,20.00,20.00,20.000000,21,...,6,F,0,35,53.0,M,0,168100,37,71509.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9681,1,2,2,2,2,10.0,15.00,15.00,15.000000,17,...,11,N,0,44,60.0,M,1,68200,38,45909.000000
9682,0,3,4,1,1,10.0,13.33,11.50,10.000000,25,...,13,A,0,44,60.0,U,1,71900,35,50530.000000
9683,1,9,14,5,7,10.0,8.78,7.71,8.800000,15,...,18,S,1,40,71.0,F,1,115700,32,40491.444249
9684,0,2,7,0,1,5.0,12.50,7.43,14.224431,6,...,16,A,0,40,60.0,M,1,106300,32,62717.000000
9685,0,8,15,7,10,5.0,4.88,4.53,5.140000,22,...,21,A,1,38,81.0,F,1,110400,36,59813.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9686 entries, 0 to 9685
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   TargetB           9686 non-null   int64
 1   GiftCnt36         9686 non-null   int64
 2   GiftCntAll        9686 non-null   int64
 3   GiftCntCard36     9686 non-null   int64
 4   GiftCntCardAll    9686 non-null   int64
 5   GiftAvgLast       9686 non-null   float64
 6   GiftAvg36         9686 non-null   float64
 7   GiftAvgAll        9686 non-null   float64
 8   GiftAvgCard36     9686 non-null   float64
 9   GiftTimeLast      9686 non-null   int64
 10  GiftTimeFirst     9686 non-null   int64
 11  PromCnt12         9686 non-null   int64
 12  PromCnt36         9686 non-null   int64
 13  PromCntAll        9686 non-null   int64
 14  PromCntCard12     9686 non-null   int64
 15  PromCntCard36     9686 non-null   int64
 16  PromCntCardAll    9686 non-null   int64
 17  StatusCat96NK     9686 non-null   object
 18  StatusCatStarAll  9686 non-null   int64
 19  DemCluster        9686 non-null   int64
 20  DemAge            9686 non-null   float64
 21  DemGender         9686 non-null   object
 22  DemHomeOwner      9686 non-null   int64
 23  DemMedHomeValue   9686 non-null   int64
 24  DemPctVeterans    9686 non-null   int64
 25  DemMedIncome      9686 non-null   float64
dtypes: float64(6), int64(18), object(2)
memory usage: 1.9+ MB

## 2. Data Partitioning

### Split into training, validation and test dataset

- **Training Dataset**: The sample of data used to fit the model.
    
- **Validation Dataset**: The sample of data used to provide an unbiased evaluation of a model fit on the training dataset while tuning model hyperparameters. The evaluation becomes more biased as skill on the validation dataset is incorporated into the model configuration.

- **Test Dataset**: The sample of data used to provide an unbiased evaluation of a final model fit on the training dataset.

In [5]:
# Create X values
X = df.drop('TargetB', axis=1)
print(X)

      GiftCnt36  GiftCntAll  GiftCntCard36  GiftCntCardAll  GiftAvgLast  \
0             2           4              1               3         17.0
1             1           8              0               3         20.0
2             6          41              3              20          6.0
3             3          12              3               8         10.0
4             1           1              1               1         20.0
...         ...         ...            ...             ...          ...
9681          2           2              2               2         10.0
9682          3           4              1               1         10.0
9683          9          14              5               7         10.0
9684          2           7              0               1          5.0
9685          8          15              7              10          5.0

      GiftAvg36  GiftAvgAll  GiftAvgCard36  GiftTimeLast  GiftTimeFirst  ...  \
0         13.50        9.25      17.000000            21             66  ...
1         20.00       15.88      14.224431            26             92  ...
2          5.17        3.73       5.000000            18            111  ...
3          8.67        8.50       8.670000             9             93  ...
4         20.00       20.00      20.000000            21             21  ...
...         ...         ...            ...           ...            ...  ...
9681      15.00       15.00      15.000000            17             24  ...
9682      13.33       11.50      10.000000            25             32  ...
9683       8.78        7.71       8.800000            15             55  ...
9684      12.50        7.43      14.224431             6             56  ...
9685       4.88        4.53       5.140000            22             57  ...

      PromCntCardAll  StatusCat96NK  StatusCatStarAll  DemCluster  DemAge  \
0                 13              A                 0           0    60.0
1                 24              A                 0          23    67.0
2                 22              S                 1           0    60.0
3                 16              E                 1           0    60.0
4                  6              F                 0          35    53.0
...              ...            ...               ...         ...     ...
9681              11              N                 0          44    60.0
9682              13              A                 0          44    60.0
9683              18              S                 1          40    71.0
9684              16              A                 0          40    60.0
9685              21              A                 1          38    81.0

      DemGender DemHomeOwner  DemMedHomeValue  DemPctVeterans  DemMedIncome
0             F            0                0               0  40491.444249
1             F            0           186800              85  40491.444249
2             M            0            87600              36  38750.000000
3             M            0           139200              27  38942.000000
4             M            0           168100              37  71509.000000
...         ...          ...              ...             ...           ...
9681          M            1            68200              38  45909.000000
9682          U            1            71900              35  50530.000000
9683          F            1           115700              32  40491.444249
9684          M            1           106300              32  62717.000000
9685          F            1           110400              36  59813.000000

[9686 rows x 25 columns]

In [6]:
# Create Y values
y = df['TargetB']
print(y)

0       0
1       0
2       1
3       1
4       0
       ..
9681    1
9682    0
9683    1
9684    0
9685    0
Name: TargetB, Length: 9686, dtype: int64

[Encoding Categorical Features](https://towardsdatascience.com/encoding-categorical-features-21a2651a065c)

In [7]:
# Instantiate LabelEncoder object
le = LabelEncoder()

# Apply le on categorical feature columns
X[['StatusCat96NK', 'DemGender']] = X[['StatusCat96NK', 'DemGender']].apply(lambda col: le.fit_transform(col))
X

,GiftCnt36,GiftCntAll,GiftCntCard36,GiftCntCardAll,GiftAvgLast,GiftAvg36,GiftAvgAll,GiftAvgCard36,GiftTimeLast,GiftTimeFirst,...,PromCntCardAll,StatusCat96NK,StatusCatStarAll,DemCluster,DemAge,DemGender,DemHomeOwner,DemMedHomeValue,DemPctVeterans,DemMedIncome
0,2,4,1,3,17.0,13.50,9.25,17.000000,21,66,...,13,0,0,0,60.0,0,0,0,0,40491.444249
1,1,8,0,3,20.0,20.00,15.88,14.224431,26,92,...,24,0,0,23,67.0,0,0,186800,85,40491.444249
2,6,41,3,20,6.0,5.17,3.73,5.000000,18,111,...,22,5,1,0,60.0,1,0,87600,36,38750.000000
3,3,12,3,8,10.0,8.67,8.50,8.670000,9,93,...,16,1,1,0,60.0,1,0,139200,27,38942.000000
4,1,1,1,1,20.0,20.00,20.00,20.000000,21,21,...,6,2,0,35,53.0,1,0,168100,37,71509.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9681,2,2,2,2,10.0,15.00,15.00,15.000000,17,24,...,11,4,0,44,60.0,1,1,68200,38,45909.000000
9682,3,4,1,1,10.0,13.33,11.50,10.000000,25,32,...,13,0,0,44,60.0,2,1,71900,35,50530.000000
9683,9,14,5,7,10.0,8.78,7.71,8.800000,15,55,...,18,5,1,40,71.0,0,1,115700,32,40491.444249
9684,2,7,0,1,5.0,12.50,7.43,14.224431,6,56,...,16,0,0,40,60.0,1,1,106300,32,62717.000000
9685,8,15,7,10,5.0,4.88,4.53,5.140000,22,57,...,21,0,1,38,81.0,0,1,110400,36,59813.000000

In [8]:
# Split into training set and testing set
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 1)

In [9]:
# Split into training set and validation set
X_train, X_val, y_train, y_val = train_test_split(
    X_train, y_train, test_size = 0.25, random_state=1)

In [10]:
# How many rows in each set
print("Training set data have {} of records, which is {}%.".format(
    X_train.shape[0], (len(X_train)/len(df)) * 100))
print("Validation set data have {} of records, which is {}%.".format(
    X_val.shape[0], (len(X_val)/len(df)) * 100))
print("Testing set data have {} of records, which is {}%.".format(
    X_test.shape[0], (len(X_test)/len(df)) * 100))

Training set data have 5811 of records, which is 59.993805492463345%.
Validation set data have 1937 of records, which is 19.99793516415445%.
Testing set data have 1938 of records, which is 20.0082593433822%.

### K-fold Cross Validation

Cross-validation is a resampling procedure used to evaluate machine learning models on a limited data sample.

**K-Fold CV** is where a given data set is split into a K number of sections/folds where each fold is used as a testing set at some point. Lets take the scenario of 5-Fold cross validation(K=5). Here, the data set is split into 5 folds. In the first iteration, the first fold is used to test the model and the rest are used to train the model. In the second iteration, 2nd fold is used as the testing set while the rest serve as the training set. This process is repeated until each fold of the 5 folds have been used as the testing set.

In [11]:
decision_tree_cv = cross_val_score(DecisionTreeClassifier(), X, y, cv = 5)
print("Mean cross-validation score: {}".format(np.mean(decision_tree_cv)))

Mean cross-validation score: 0.524364115670451

**Pros of K-Fold CV:**
- Due to sample variability between training and test set, our model gives a better prediction on training data but fail to generalize on test data. This leads to a low training error rate but a high test error rate. This problem can be solved using cross validation to **reduce bias**

**Cons of K-Fold CV:**
- The training algorithm is **computationally intensive** as the algorithm has to be rerun from scratch k times.

## 3. Decision Tree

### 3.1 Build a Decision Tree classifier

In [12]:
# Decision tree classifier
decision_tree = DecisionTreeClassifier(random_state = 0).fit(np.asmatrix(X_train), y_train)

### 3.2 Performance of the model against training data

In [13]:
decision_tree.score(X_train, y_train)

1.0

### 3.3 Performance of the model against validation data

In [14]:
decision_tree.score(X_val, y_val)

0.5126484254001032

### 3.4 Performance of the model against test data

In [15]:
decision_tree.score(X_test, y_test)

0.5149638802889577

*Predict using training data tends overfitting whereas test data don't.*

### 3.5 Performance Metrics of model

In [16]:
y_pred = decision_tree.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.51      0.50      0.51       957
           1       0.52      0.53      0.52       981

    accuracy                           0.51      1938
   macro avg       0.51      0.51      0.51      1938
weighted avg       0.51      0.51      0.51      1938

### 3.6 Important Features

In [17]:
features = []
for feature in zip(X.columns, decision_tree.feature_importances_):
    #print(feature)
    features.append(feature)

In [18]:
featureDF = pd.DataFrame(features, columns=['feature','importance'])
featureDF

             feature  importance
0          GiftCnt36    0.032710
1         GiftCntAll    0.026756
2      GiftCntCard36    0.013857
3     GiftCntCardAll    0.033702
4        GiftAvgLast    0.022194
5          GiftAvg36    0.045336
6         GiftAvgAll    0.072371
7      GiftAvgCard36    0.047666
8       GiftTimeLast    0.051014
9      GiftTimeFirst    0.050903
10         PromCnt12    0.026556
11         PromCnt36    0.039115
12        PromCntAll    0.038259
13     PromCntCard12    0.011096
14     PromCntCard36    0.030007
15    PromCntCardAll    0.032955
16     StatusCat96NK    0.006921
17  StatusCatStarAll    0.004367
18        DemCluster    0.073309
19            DemAge    0.069367
20         DemGender    0.016473
21      DemHomeOwner    0.007301
22   DemMedHomeValue    0.104156
23    DemPctVeterans    0.063819
24      DemMedIncome    0.079788

In [19]:
# Top 5 important features
featureDF.sort_values(by = 'importance', ascending = False).head(5)

            feature  importance
22  DemMedHomeValue    0.104156
24     DemMedIncome    0.079788
18       DemCluster    0.073309
6        GiftAvgAll    0.072371
19           DemAge    0.069367

### 3.7 Visualise the structure of Decision Tree

<span style="color:red">failed to execute [‘dot’, ‘-Tsvg’], make sure the Graphviz executables are on your systems’ PATH</span>


Refer to [Graphviz problem on Windows](https://discuss.mxnet.io/t/graphviz-problem-on-windows/712)

In [20]:
import os
os.environ["PATH"] += os.pathsep + r'C:\Users\FORGE-15 I7\Anaconda3\pkgs\graphviz-2.38-hfd603c8_2\Library\bin\graphviz'

In [21]:
#tree.plot_tree(decision_tree);

In [24]:
"""
png_bytes = graph.pipe(format='png')
with open('dtree_pipe.png','wb') as f:
    f.write(png_bytes)

from IPython.display import Image
Image(png_bytes)
"""

graph = Source( tree.export_graphviz(decision_tree, out_file=None, feature_names=X.columns))

# Save into png file
#graph.format = 'png'
#graph.render('dtree_render',view=True)

# Display decision tree
#SVG(graph.pipe(format='svg'))